[[mounts]]
  source = "layouts"
  target = "layouts"

[[mounts]]
  source = "node_modules/@hyas/images/layouts"
  target = "layouts"

[[imports]]
  path = "github.com/rootwork/hugo-module-gallery-grid"
