# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - name: Setup
    before: |
      export HOMEBREW_NO_INSTALL_CLEANUP=TRUE
      brew install hugo
      yarn install --immutable --immutable-cache
      cd hugo && npm ci
      cd ..
    init: echo "Your version of Hugo is `hugo version`"
    command: yarn serve:gitpod

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 1313
    onOpen: open-preview
